### ISSUE TITLE
An error while running on my device

### ISSUE THREAD

**Issue by noshamedevil** [RivaanRanawat/flutter-amazon-clone-tutorial#1]
Hello,
Hope you can help me and all the others who are visiting this repo by helping me to solve this simple error which i am facing while trying to sign up or sign in using the app on my android device, attaching a photo of the same
![image](https://user-images.githubusercontent.com/62800600/174152613-de2db06f-5784-475f-b623-b8f85cbd6f59.png)

Thanks in advance

**Comment by khshaaban-dev** [comment]
Hello 
thank you for this coursre 
when I test app is it work  without internet connection expect to show snackbar show that for example socketException
 but this error was faired.

//==============================================================================
E/flutter ( 8733):   ChangeNotifierProvider<UserProvider>
E/flutter ( 8733):   _NestedHook
E/flutter ( 8733):   MultiProvider
E/flutter ( 8733):   [root]
E/flutter ( 8733): Typically, the ScaffoldMessenger widget is introduced by the MaterialApp at the top of your application widget tree.
E/flutter ( 8733): #0      debugCheckHasScaffoldMessenger.<anonymous closure>
debug.dart:170
E/flutter ( 8733): #1      debugCheckHasScaffoldMessenger
debug.dart:181
E/flutter ( 8733): #2      ScaffoldMessenger.of
scaffold.dart:148
E/flutter ( 8733): #3      showSnackBar
utils.dart:7
E/flutter ( 8733): #4      AuthService.getUserData
auth_service.dart:142
E/flutter ( 8733): <asynchronous suspension>
E/flutter ( 8733):
//==============================================================================

again thank you so match.
